unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'vagrant-vbguest is not installed! Please install it with this command: vagrant plugin install vagrant-vbguest'
end

$client_script = <<-SCRIPT
route del default
route add default gw 192.168.1.1
SCRIPT

$natgw_script = <<-SCRIPT
sysctl net.inet.ip.forwarding=1
echo realnet  = "em0" >/etc/pf.conf
internal = "em1" >>/etc/pf.conf
fakenet  = "em2" >>/etc/pf.conf
pass out on $fakenet from 192.168.1.0/24 to any nat-to $fakenet >>/etc/pf.conf
pass out on $realnet from 192.168.1.0/24 to any nat-to $realnet >>/etc/pf.conf

pfctl -f /etc/pf.conf
SCRIPT

$server_script = <<-SCRIPT
apt-get -y install stun
stund -h 172.16.0.10 -a 172.16.0.11 &
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "client1" do |client1|
    client1.vm.box = "debian/jessie64"
    client1.vm.hostname = 'client1'
    client1.vm.network :private_network, ip: "192.168.1.10", virtualbox__intnet: "client_net1"
    client1.vm.provision "shell", inline: $client_script
    client1.vm.synced_folder "..", "/winter-is-coming"
  end
  config.vm.define "client2" do |client2|
    client2.vm.box = "debian/jessie64"
    client2.vm.hostname = 'client2'
    client2.vm.network :private_network, ip: "192.168.1.10", virtualbox__intnet: "client_net2"
    client2.vm.provision "shell", inline: $client_script
    client2.vm.synced_folder "..", "/winter-is-coming"
  end

  config.vm.define "natgw1" do |natgw1|
    natgw1.vm.box      = "generic/openbsd6"
    natgw1.vm.hostname = "natgw1"
    natgw1.vm.network  :private_network, ip: "192.168.1.1", virtualbox__intnet: "client_net1"
    natgw1.vm.network  :private_network, ip: "172.16.0.1",  virtualbox__intnet: "fake_internet"
    natgw1.vm.provision "shell", inline: $natgw_script
  end

  config.vm.define "natgw2" do |natgw2|
    natgw2.vm.box      = "generic/openbsd6"
    natgw2.vm.hostname = "natgw2"
    natgw2.vm.network  :private_network, ip: "192.168.1.1", virtualbox__intnet: "client_net2"
    natgw2.vm.network  :private_network, ip: "172.16.0.2",  virtualbox__intnet: "fake_internet"
    natgw2.vm.provision "shell", inline: $natgw_script
  end

  config.vm.define "server" do |server|
    server.vm.box      = "debian/jessie64"
    server.vm.hostname = "server"
    server.vm.network  :private_network, ip: "172.16.0.10", virtualbox__intnet: "fake_internet"
    server.vm.network  :private_network, ip: "172.16.0.11", virtualbox__intnet: "fake_internet"
    server.vm.provision "shell", inline: $server_script
  end
end
